In [31]:
import torch
import torch.nn as nn

# Example of target with class indices
loss = nn.CrossEntropyLoss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.empty(3, dtype=torch.long).random_(5)
output = loss(input, target)
output.backward()

max_scores, max_idx = input.max(dim=1)
print(max_idx)
print(target)

# Example of target with class probabilities
input = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5).softmax(dim=1)
output = loss(input, target)
output.backward()

print(input)
print(target)

tensor([0, 3, 0])
tensor([4, 1, 4])
tensor([[-0.9474,  0.4423,  1.4375, -0.1625, -0.9571],
        [-0.7990, -0.8211,  1.2274,  0.7918, -0.2556],
        [ 2.4240,  0.0339, -2.0204, -1.6073,  0.7701]], requires_grad=True)
tensor([[0.3598, 0.1968, 0.0514, 0.1722, 0.2198],
        [0.0653, 0.2300, 0.0901, 0.5712, 0.0435],
        [0.1034, 0.0357, 0.0619, 0.0634, 0.7357]])
